version: '3.5'
services:
    feishin:
        container_name: feishin-auth-test
        image: feishin-auth:v0.1.0
        restart: unless-stopped
        ports:
            - 9180:9180
        environment:
            - SERVER_NAME=jellyfin # pre defined server name
            - SERVER_LOCK=false # When true AND name/type/url are set, only username/password can be toggled
            - SERVER_TYPE=navidrome # navidrome also works
            - SERVER_URL=https://music.28.al # http://address:port
            - WEB_TITLE=Myn
            - USERNAME=hertz # pre defined username
            - PASSWORD=VlM1lkUO # pre defined password
            - ALLOW_CODE=123 # used for some authentications
            - LEGACY_AUTHENTICATION=false # When SERVER_LOCK is true, sets the legacyauth flag for server authentication (true or false)
            - ANALYTICS_DISABLED=false # Set to true to disable Umami analytics tracking
